version: '3'
services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/app
    volumes:
      - ./volumes:/usr/app/src
    ports:
      - "3000:3000"
    restart: always  